[package]
name = "knight-bot"
version = "1.0.0"
authors = ["Cyber Knight <npv12@iitbbs.ac.in>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grammers = { git = "https://github.com/Lonami/grammers" }
grammers-client = { git = "https://github.com/Lonami/grammers" }
grammers-session = { git = "https://github.com/Lonami/grammers" }
log = { version = "0.4.17" }
simple_logger = "2.3.0"
tokio = { version = "1.5.0", features = ["full"] }
