[package]
name = "knight-bot"
version = "1.0.0"
authors = ["Cyber Knight <npv12@iitbbs.ac.in>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getrandom = "0.2"
grammers-client = { git = "https://github.com/Lonami/grammers" }
grammers-session = { git = "https://github.com/Lonami/grammers" }
log = { version = "0.4.17" }
pretty_env_logger = "0.4.0"
serde = { version = "1.0.137", features = ["derive"]}
tokio = { version = "1.5.0", features = ["full"] }
toml = "0.5.9"

[features]
default = ["html"]
html = ["grammers-client/html"]
