name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose
    - name: Upload to server
      uses: "burnett01/rsync-deployments@5.2.1"
      with:
        switches: -rvz
        remote_host: ${{ secrets.SERVER_IP }}
        remote_user: ${{ secrets.SERVER_USERNAME }}
        remote_key: ${{ secrets.SSH_KEY }}
        remote_key_pass: ${{ secrets.SSH_PASSWORD }}
        path: "./target/release/knight-bot"
        remote_path: "/home/knight/"
